services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - shared
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=passw123
    restart: always
  redis:
    container_name: rediscache
    image: redis:latest
    command: redis-server --requirepass pass
    ports:
      - "6379:6379"
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - 9200:9200
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=pass
    networks:
      - shared
  web:
    build: .
    container_name: kapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081;http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - elasticsearch
    networks:
      - shared

networks:
  shared:
    driver: bridge

volumes:
  elastic-volume:
  logs-folder:
    name: ${log_rabbitmq}
    driver: local